package zombie.entity.components.crafting;

public enum InputFlag {
   HandcraftOnly,
   AutomationOnly,
   IsFull,
   NotFull,
   ItemIsUses,
   ItemIsFluid,
   ItemIsEnergy,
   IsEmpty,
   NotEmpty,
   Prop1,
   Prop2,
   ToolLeft,
   ToolRight,
   IsDamaged,
   IsUndamaged,
   IsWholeFoodItem,
   IsEmptyContainer,
   IsUncookedFoodItem,
   IsCookedFoodItem,
   IsNotDull,
   IsHeadPart,
   IsSharpenable,
   DontPutBack,
   InheritColor,
   InheritCondition,
   InheritSharpness,
   InheritHeadCondition,
   MayDegrade,
   MayDegradeLight,
   MayDegradeHeavy,
   SharpnessCheck,
   InheritUses,
   AllowFrozenItem,
   AllowRottenItem,
   NoBrokenItems,
   AllowDestroyedItem,
   IsWorn,
   IsNotWorn,
   InheritFoodAge,
   InheritAmmunition,
   CopyClothing,
   AllowFavorite,
   InheritFavorite,
   FakeOutput,
   DontReplace;

   private InputFlag() {
   }
}
