package zombie.core.physics;

public enum RagdollBodyPart {
   BODYPART_PELVIS,
   BODYPART_SPINE,
   BODYPART_HEAD,
   BODYPART_LEFT_UPPER_LEG,
   BODYPART_LEFT_LOWER_LEG,
   BODYPART_RIGHT_UPPER_LEG,
   BODYPART_RIGHT_LOWER_LEG,
   BODYPART_LEFT_UPPER_ARM,
   BODYPART_LEFT_LOWER_ARM,
   BODYPART_RIGHT_UPPER_ARM,
   BODYPART_RIGHT_LOWER_ARM,
   BODYPART_COUNT;

   private RagdollBodyPart() {
   }
}
